webtalk_init -webtalk_dir D:\\GIT\\Zybo\\VGA\\source\\vivado\\hw\\zybo_bsd\\zybo_bsd.sdk\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "jue ene 29 19:49:12 2015" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2014.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2014.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "202681517_1777501924_210586115_447" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "em152sjfjkrkt75p8fvl5d38of" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2014.2_7" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "7" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 7 , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Service Pack 1  (build 7601)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-2670QM CPU @ 2.20GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2195 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1422551856306" -context "sdk\\\\bsp/1422551856306"
webtalk_add_data -client sdk -key hwid -value "1421399255580" -context "sdk\\\\bsp/1422551856306"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1422551856306"
webtalk_add_data -client sdk -key apptemplate -value "empty_application" -context "sdk\\\\bsp/1422551856306"
webtalk_add_data -client sdk -key uid -value "1422551860961" -context "sdk\\\\application/1422551860961"
webtalk_add_data -client sdk -key hwid -value "1421399255580" -context "sdk\\\\application/1422551860961"
webtalk_add_data -client sdk -key bspid -value "1422551856306" -context "sdk\\\\application/1422551860961"
webtalk_add_data -client sdk -key newbsp -value "true" -context "sdk\\\\application/1422551860961"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1422551860961"
webtalk_add_data -client sdk -key apptemplate -value "empty_application" -context "sdk\\\\application/1422551860961"
webtalk_transmit -clientid 1662825696 -regid "202681517_1777501924_210586115_447" -xml D:\\GIT\\Zybo\\VGA\\source\\vivado\\hw\\zybo_bsd\\zybo_bsd.sdk\\webtalk\\usage_statistics_ext_sdk.xml -html D:\\GIT\\Zybo\\VGA\\source\\vivado\\hw\\zybo_bsd\\zybo_bsd.sdk\\webtalk\\usage_statistics_ext_sdk.html -wdm D:\\GIT\\Zybo\\VGA\\source\\vivado\\hw\\zybo_bsd\\zybo_bsd.sdk\\webtalk\\sdk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
