# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/base.xdc

# Block Designs: bd/system/system.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system || ORIG_REF_NAME==system}]

# IP: bd/system/ip/system_BTNs_4Bits_0/system_BTNs_4Bits_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_BTNs_4Bits_0 || ORIG_REF_NAME==system_BTNs_4Bits_0}]

# IP: bd/system/ip/system_LEDs_4Bits_1/system_LEDs_4Bits_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_LEDs_4Bits_1 || ORIG_REF_NAME==system_LEDs_4Bits_1}]

# IP: bd/system/ip/system_SWs_4Bits_2/system_SWs_4Bits_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_SWs_4Bits_2 || ORIG_REF_NAME==system_SWs_4Bits_2}]

# IP: bd/system/ip/system_axi_dispctrl_0_0/system_axi_dispctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_dispctrl_0_0 || ORIG_REF_NAME==system_axi_dispctrl_0_0}]

# IP: bd/system/ip/system_axi_dispctrl_1_1/system_axi_dispctrl_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_dispctrl_1_1 || ORIG_REF_NAME==system_axi_dispctrl_1_1}]

# IP: bd/system/ip/system_axi_i2s_adi_1_0/system_axi_i2s_adi_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_i2s_adi_1_0 || ORIG_REF_NAME==system_axi_i2s_adi_1_0}]

# IP: bd/system/ip/system_axi_mem_intercon_0/system_axi_mem_intercon_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_mem_intercon_0 || ORIG_REF_NAME==system_axi_mem_intercon_0}]

# IP: bd/system/ip/system_axi_protocol_converter_0_0/system_axi_protocol_converter_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_protocol_converter_0_0 || ORIG_REF_NAME==system_axi_protocol_converter_0_0}]

# IP: bd/system/ip/system_axi_vdma_0_0/system_axi_vdma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_vdma_0_0 || ORIG_REF_NAME==system_axi_vdma_0_0}]

# IP: bd/system/ip/system_axi_vdma_1_1/system_axi_vdma_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_vdma_1_1 || ORIG_REF_NAME==system_axi_vdma_1_1}]

# IP: bd/system/ip/system_ground_0/system_ground_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_ground_0 || ORIG_REF_NAME==system_ground_0}]

# IP: bd/system/ip/system_hdmi_tx_0_0/system_hdmi_tx_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_hdmi_tx_0_0 || ORIG_REF_NAME==system_hdmi_tx_0_0}]

# IP: bd/system/ip/system_processing_system7_0_0/system_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_processing_system7_0_0 || ORIG_REF_NAME==system_processing_system7_0_0}]

# IP: bd/system/ip/system_processing_system7_0_axi_periph_2/system_processing_system7_0_axi_periph_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_processing_system7_0_axi_periph_2 || ORIG_REF_NAME==system_processing_system7_0_axi_periph_2}]

# IP: bd/system/ip/system_xbar_2/system_xbar_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xbar_2 || ORIG_REF_NAME==system_xbar_2}]

# IP: bd/system/ip/system_vdd_1/system_vdd_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_vdd_1 || ORIG_REF_NAME==system_vdd_1}]

# IP: bd/system/ip/system_xlconstant_0_2/system_xlconstant_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xlconstant_0_2 || ORIG_REF_NAME==system_xlconstant_0_2}]

# IP: bd/system/ip/system_xbar_3/system_xbar_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xbar_3 || ORIG_REF_NAME==system_xbar_3}]

# IP: bd/system/ip/system_m00_regslice_16/system_m00_regslice_16.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_m00_regslice_16 || ORIG_REF_NAME==system_m00_regslice_16}]

# IP: bd/system/ip/system_m01_regslice_17/system_m01_regslice_17.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_m01_regslice_17 || ORIG_REF_NAME==system_m01_regslice_17}]

# IP: bd/system/ip/system_m02_regslice_18/system_m02_regslice_18.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_m02_regslice_18 || ORIG_REF_NAME==system_m02_regslice_18}]

# IP: bd/system/ip/system_m03_regslice_19/system_m03_regslice_19.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_m03_regslice_19 || ORIG_REF_NAME==system_m03_regslice_19}]

# IP: bd/system/ip/system_m04_regslice_20/system_m04_regslice_20.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_m04_regslice_20 || ORIG_REF_NAME==system_m04_regslice_20}]

# IP: bd/system/ip/system_m05_regslice_21/system_m05_regslice_21.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_m05_regslice_21 || ORIG_REF_NAME==system_m05_regslice_21}]

# IP: bd/system/ip/system_m06_regslice_22/system_m06_regslice_22.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_m06_regslice_22 || ORIG_REF_NAME==system_m06_regslice_22}]

# IP: bd/system/ip/system_m07_regslice_23/system_m07_regslice_23.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_m07_regslice_23 || ORIG_REF_NAME==system_m07_regslice_23}]

# IP: bd/system/ip/system_auto_pc_7/system_auto_pc_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_pc_7 || ORIG_REF_NAME==system_auto_pc_7}]

# XDC: bd/system/system_ooc.xdc
